default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  username: "root"
  password: "Iamalone0711"
  database: "solomo_development"

development:
  <<: *default
  database: "solomo_development"

test:
  <<: *default
  database: "solomo_test<%= ENV['TEST_ENV_NUMBER'] %>"

production:
  <<: *default
  database: "solomo_production"
