default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: "postgres"
  password: "iamalone"
  database: "solomo_development"

development:
  <<: *default
  database: "solomo_development"

test:
  <<: *default
  database: "solomo_test<%= ENV['TEST_ENV_NUMBER'] %>"

production:
  <<: *default
  database: "solomo_production"
  username: rails
  password: WiNTIYaj6v
