default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  timeout: 5000
  username: "postgres"
  password: "123456"
  database: "solomo_development"

development:
  <<: *default
  database: "solomo_development"

test:
  <<: *default
  database: "solomo_test<%= ENV['TEST_ENV_NUMBER'] %>"

production:
  <<: *default
  host: 'ec2-54-83-198-111.compute-1.amazonaws.com'
  database: "d5pfltdrq8594q"
  username: yddixlenahknqd
  password: jy24KnMlHxi4892oQETUezurH5
  port: 5432
