# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1a9c379bf4c1f258fe53c22c5b843aaad273634034223898749ed58b4f4099aa1bf5a01da8d336793733843fb38ad4d98665106994ec0d382facf5c62705ca1c
  fb_app_id: 537496736415112
  fb_app_secret: 7bb1111204f4f08911c2726a684e1d13
  domain_name: 'solomo.vn'
test:
  secret_key_base: ca788541352e46d2d69addf749ad90dcb6818b1f272ca7f2d568ececc6563f2deddc04d87f6042e9ba86488740935a1cba2bd899a5d20c072beba0fa62f37df1
  fb_app_id: 537496736415112
  fb_app_secret: 7bb1111204f4f08911c2726a684e1d13
  domain_name: 'solomo.vn'
# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: ca788541352e46d2d69addf749ad90dcb6818b1f272ca7f2d568ececc6563f2deddc04d87f6042e9ba86488740935a1cba2bd899a5d20c072beba0fa62f37df1
  fb_app_id: 537496736415112
  fb_app_secret: 7bb1111204f4f08911c2726a684e1d13
  domain_name: 'solomo.vn'
  aws_access_key: AKIAIJMWBP4HLNZK6GOA
  aws_secret_key: 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
